# Generated by Django 2.2.3 on 2019-07-19 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200, verbose_name='评论内容')),
                ('article', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Blog.ArticleTable', verbose_name='父级分类')),
            ],
        ),
    ]
