# Generated by Django 2.2.3 on 2019-07-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20190721_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletable',
            name='comment_status',
            field=models.CharField(choices=[('c', '关闭'), ('o', '开启')], default='o', max_length=1, verbose_name='评论状态'),
        ),
        migrations.AlterField(
            model_name='articletable',
            name='status',
            field=models.CharField(choices=[('c', '删除'), ('d', '草稿'), ('n', '正常')], default='n', max_length=1, verbose_name='文章状态'),
        ),
        migrations.AlterField(
            model_name='articletable',
            name='type',
            field=models.CharField(choices=[('t', '技术'), ('g', '闲聊')], default='g', max_length=1, verbose_name='类型'),
        ),
    ]
