# Generated by Django 2.2.3 on 2019-07-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_auto_20190722_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsettingstable',
            name='beiancode',
            field=models.CharField(blank=True, default='123456', max_length=2000, null=True, verbose_name='备案号'),
        ),
        migrations.AlterField(
            model_name='blogsettingstable',
            name='gongan_beiancode',
            field=models.TextField(blank=True, default='123456', max_length=2000, null=True, verbose_name='公安备案号'),
        ),
    ]
