# Generated by Django 2.2.3 on 2019-07-23 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_auto_20190722_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogsettingstable',
            name='google_adsense_codes',
        ),
        migrations.RemoveField(
            model_name='blogsettingstable',
            name='show_google_adsense',
        ),
        migrations.AlterField(
            model_name='blogsettingstable',
            name='article_sub_length',
            field=models.CharField(default=300, max_length=20, verbose_name='文章摘要分隔符'),
        ),
    ]
