# Generated by Django 2.2.3 on 2019-07-23 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_auto_20190723_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsettingstable',
            name='article_count',
            field=models.IntegerField(default=10, verbose_name='分页文章数目'),
        ),
    ]
