# Generated by Django 2.2.3 on 2019-07-23 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_blogsettingstable_article_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogsettingstable',
            old_name='article_sub_length',
            new_name='article_sub_split_str',
        ),
    ]
